import { Lead } from "./types";

export const initialLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Thiago Mendes",
    phone: "(11) 98211-3050",
    source: "Zap Imóveis",
    stage: "Novo Lead",
    kanbanType: "atendimento",
    score: 25,
    category: "Frio",
    createdAt: "19/06/2026",
    avatarColor: "bg-blue-100 text-blue-700",
    profile: {
      city: "São Paulo",
      bairro: "Pinheiros",
      tipo: "Apartamento",
      faixaInvestimento: "Até R$ 800.000",
      formaPagamento: "",
      prazoCompra: "Não urgente",
      perfilComprador: "Pesquisa Inicial",
    },
  },
  {
    id: "lead-2",
    name: "Camila Prado",
    phone: "(11) 97155-2244",
    source: "Instagram Ads",
    stage: "Atendimento IA",
    kanbanType: "atendimento",
    score: 48,
    category: "Morno",
    createdAt: "18/06/2026",
    avatarColor: "bg-purple-100 text-purple-700",
    profile: {
      city: "Barueri",
      bairro: "Alphaville",
      tipo: "Casa",
      faixaInvestimento: "R$ 2.500.000 a R$ 3.500.000",
      formaPagamento: "Financiamento Bancário",
      prazoCompra: "Dentro de 6 meses",
      perfilComprador: "Família mudando de apto para casa",
    },
  },
  {
    id: "lead-3",
    name: "Fernando Souza",
    phone: "(62) 99820-1122",
    source: "Google Ads",
    stage: "Atendimento Humano",
    kanbanType: "atendimento",
    score: 60,
    category: "Morno",
    createdAt: "17/06/2026",
    avatarColor: "bg-amber-100 text-amber-700",
    profile: {
      city: "Goiânia",
      bairro: "Setor Marista",
      tipo: "Haras / Fazenda",
      faixaInvestimento: "R$ 5.000.000 a R$ 8.000.000",
      formaPagamento: "À vista com permuta",
      prazoCompra: "Curto Prazo (imediatamente)",
      perfilComprador: "Criador de Cavalos Manga-larga",
    },
  },
  {
    id: "lead-4",
    name: "Juliana Dias",
    phone: "(19) 99310-8800",
    source: "WhatsApp Orgânico",
    stage: "Qualificado",
    kanbanType: "atendimento",
    score: 85,
    category: "Quente",
    createdAt: "19/06/2026",
    avatarColor: "bg-green-100 text-green-700",
    profile: {
      city: "Sorocaba",
      bairro: "Área Rural",
      tipo: "Fazenda Produtiva",
      faixaInvestimento: "Até R$ 15.000.000",
      formaPagamento: "Parcelamento Safra",
      prazoCompra: "Imediato",
      perfilComprador: "Grupo Agrícola (Expansão)",
    },
  },
  // Oportunidades
  {
    id: "lead-5",
    name: "Ricardo Albuquerque",
    phone: "(11) 98112-9011",
    source: "Indicação",
    stage: "Visita Agendada",
    kanbanType: "oportunidade",
    score: 78,
    category: "Quente",
    createdAt: "15/06/2026",
    avatarColor: "bg-indigo-100 text-indigo-700",
    profile: {
      city: "São Paulo",
      bairro: "Jardins",
      tipo: "Apartamento Premium",
      faixaInvestimento: "R$ 1.800.000",
      formaPagamento: "À vista",
      prazoCompra: "Imediato",
      perfilComprador: "Casal jovem com filhos pequenos",
    },
  },
  {
    id: "lead-6",
    name: "Patrícia Menezes",
    phone: "(11) 99120-4030",
    source: "Site Fluow",
    stage: "Proposta",
    kanbanType: "oportunidade",
    score: 90,
    category: "Quente",
    createdAt: "10/06/2026",
    avatarColor: "bg-rose-100 text-rose-700",
    profile: {
      city: "São Paulo",
      bairro: "Moema",
      tipo: "Studio Loft",
      faixaInvestimento: "R$ 650.000",
      formaPagamento: "Financiamento 80%",
      prazoCompra: "Até 1 mês",
      perfilComprador: "Investidora para Locação pelo Airbnb",
    },
  },
  // Pós-venda
  {
    id: "lead-7",
    name: "Eduardo Moreira",
    phone: "(11) 97721-0011",
    source: "OLX",
    stage: "Documentação",
    kanbanType: "posvenda",
    score: 100,
    category: "Quente",
    createdAt: "01/06/2026",
    avatarColor: "bg-emerald-100 text-emerald-700",
    profile: {
      city: "Barueri",
      bairro: "Alphaville",
      tipo: "Casa",
      faixaInvestimento: "R$ 3.400.000",
      formaPagamento: "Consórcio + Recursos Próprios",
      prazoCompra: "Finalizado",
      perfilComprador: "Empresário local",
    },
  },
];
